/**
 * Generated by scripts/build-ts-bindings.mjs — DO NOT EDIT BY HAND.
 * Source: specs/vrc/relationship/issue/0.1/payload.schema.json
 */

/**
 * Delivers one party's signed Verifiable Relationship Credential to the other within an accepted relationship exchange. Performed once in each direction; the response is a delivery receipt that does not echo the credential back.
 */
export interface VRCRelationshipIssuePayload {
  /**
   * A signed W3C Verifiable Relationship Credential (opaque here). Its issuer MUST be the issuing party's relationship DID and its credential subject MUST name the receiving party's relationship DID — the values the accepted proposal exchanged.
   */
  vrc: {};
  /**
   * Multibase-encoded multihash over the credential — the registry's converged digest form — so the delivery can be tied to later references to the credential without re-hashing.
   */
  vrcDigestMultibase?: string;
  ext?: Ext;
}
/**
 * Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.
 */
export interface Ext {
  [k: string]: unknown | undefined;
}
/**
 * The delivery receipt: the receiving party accepted and stored the credential. A refusal is a trust-task-error, never a receipt with received: false.
 */
export interface VRCRelationshipIssueResponsePayload {
  /**
   * Always true: a refusal travels as a trust-task-error. Present so acceptance is explicit rather than inferred from the response's existence.
   */
  received: true;
  /**
   * Echo of the delivered credential's digest, computed by the receiver, so a mismatch between what was sent and what was stored is detectable in-band.
   */
  vrcDigestMultibase?: string;
  ext?: Ext;
}

/** Trust Task type URI. */
export const TYPE_URI = "https://trusttasks.org/spec/vrc/relationship/issue/0.1" as const;

/** Stable alias for this specification's request payload shape. */
export type Payload = VRCRelationshipIssuePayload;

/** Trust Task response type URI (request type URI + "#response"). */
export const RESPONSE_TYPE_URI = "https://trusttasks.org/spec/vrc/relationship/issue/0.1#response" as const;

/** Stable alias for this specification's success-response payload shape. */
export type Response = VRCRelationshipIssueResponsePayload;

/**
 * SPEC.md §7.2 policy for the request variant, from this specification's
 * front matter. Pass to `consumeInbound` — items 5b, 7 and 8 are
 * per-specification and cannot be derived from the document alone.
 */
export const SPEC = {
  typeUri: TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
} as const;

/**
 * SPEC.md §7.2 policy for the success-response variant. `isRecipientRequired`
 * tracks the *issuer* party's requirement because a response swaps the
 * parties (§7.3 item 5).
 */
export const RESPONSE_SPEC = {
  typeUri: RESPONSE_TYPE_URI,
  isBearer: false,
  isProofRequired: false,
  isRecipientRequired: true,
} as const;
