/**
 * Generated by scripts/build-ts-bindings.mjs — DO NOT EDIT BY HAND.
 * Source: specs/witness/session/0.1/payload.schema.json
 */

/**
 * Opens a witness ceremony as its own exchange, nested in a relationship exchange via parentThreadId. The response issues the session challenge; the request document's id is the value a VWC later carries as taskContext.
 */
export interface WitnessSessionPayload {
  /**
   * The relationship DIDs of the exchange to be witnessed — the pairwise values the relationship proposal exchanged, in either order.
   *
   * @minItems 2
   * @maxItems 2
   */
  parties: [string, string];
  ext?: Ext;
}
/**
 * Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.
 */
export interface Ext {
  [k: string]: unknown | undefined;
}
/**
 * The session challenge, issued under the REQUIRED proof. Presentations under witness/session/submit bind to {challenge, domain}.
 */
export interface WitnessSessionResponsePayload {
  /**
   * A fresh, unpredictable, single-use value the ceremony's presentations bind to. A witness MUST NOT reuse a challenge across sessions.
   */
  challenge: string;
  /**
   * The domain the presentations bind alongside the challenge, identifying this witness's verification context.
   */
  domain: string;
  ext?: Ext;
}

/** Trust Task type URI. */
export const TYPE_URI = "https://trusttasks.org/spec/witness/session/0.1" as const;

/** Stable alias for this specification's request payload shape. */
export type Payload = WitnessSessionPayload;

/** Trust Task response type URI (request type URI + "#response"). */
export const RESPONSE_TYPE_URI = "https://trusttasks.org/spec/witness/session/0.1#response" as const;

/** Stable alias for this specification's success-response payload shape. */
export type Response = WitnessSessionResponsePayload;

/**
 * SPEC.md §7.2 policy for the request variant, from this specification's
 * front matter. Pass to `consumeInbound` — items 5b, 7 and 8 are
 * per-specification and cannot be derived from the document alone.
 */
export const SPEC = {
  typeUri: TYPE_URI,
  isBearer: false,
  isProofRequired: false,
  isRecipientRequired: true,
} as const;

/**
 * SPEC.md §7.2 policy for the success-response variant. `isRecipientRequired`
 * tracks the *issuer* party's requirement because a response swaps the
 * parties (§7.3 item 5).
 */
export const RESPONSE_SPEC = {
  typeUri: RESPONSE_TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
} as const;
