/**
 * Generated by scripts/build-ts-bindings.mjs — DO NOT EDIT BY HAND.
 * Source: specs/vrc/relationship/propose/0.1/payload.schema.json
 */

/**
 * One person proposes a peer-to-peer relationship to another, naming the pairwise DID they will use for it. The counterparty accepts or declines; a decline is a trust-task-error carrying `vrc/relationship/propose:declined`.
 */
export interface VRCRelationshipProposePayload {
  /**
   * The pairwise DID the proposing party will use for this relationship. Minted for this relationship — a producer MUST NOT carry a long-term identifier here, which would make every later presentation of the resulting credentials linkable.
   */
  relationshipDid: string;
  /**
   * Whether the proposing party requests a witnessed exchange. Intent only: the ceremony itself is negotiated under the witness/* specifications, as its own exchange nested via parentThreadId. Absent means unwitnessed.
   */
  witnessed?: boolean;
  /**
   * Why the proposing party is asking, in their own words. A hint reaching a human; the counterparty is under no obligation to honour it and MUST NOT treat its absence as a defect.
   */
  reason?: string;
  ext?: Ext;
}
/**
 * Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.
 */
export interface Ext {
  [k: string]: unknown | undefined;
}
/**
 * The counterparty's acceptance. A decline is a trust-task-error, never a response with accept: false.
 */
export interface VRCRelationshipProposeResponsePayload {
  /**
   * Always true: a decline travels as a trust-task-error so that refusals share one path and one set of routing rules (SPEC.md §8.1). Present so the acceptance is explicit rather than inferred from the response's existence.
   */
  accept: true;
  /**
   * The pairwise DID the counterparty will use for this relationship, under the same non-linkability obligation as the request's.
   */
  relationshipDid: string;
  ext?: Ext;
}

/** Trust Task type URI. */
export const TYPE_URI = "https://trusttasks.org/spec/vrc/relationship/propose/0.1" as const;

/** Stable alias for this specification's request payload shape. */
export type Payload = VRCRelationshipProposePayload;

/** Trust Task response type URI (request type URI + "#response"). */
export const RESPONSE_TYPE_URI = "https://trusttasks.org/spec/vrc/relationship/propose/0.1#response" as const;

/** Stable alias for this specification's success-response payload shape. */
export type Response = VRCRelationshipProposeResponsePayload;

/**
 * SPEC.md §7.2 policy for the request variant, from this specification's
 * front matter. Pass to `consumeInbound` — items 5b, 7 and 8 are
 * per-specification and cannot be derived from the document alone.
 */
export const SPEC = {
  typeUri: TYPE_URI,
  isBearer: false,
  isProofRequired: false,
  isRecipientRequired: true,
} as const;

/**
 * SPEC.md §7.2 policy for the success-response variant. `isRecipientRequired`
 * tracks the *issuer* party's requirement because a response swaps the
 * parties (§7.3 item 5).
 */
export const RESPONSE_SPEC = {
  typeUri: RESPONSE_TYPE_URI,
  isBearer: false,
  isProofRequired: false,
  isRecipientRequired: true,
} as const;
