/**
 * Generated by scripts/build-ts-bindings.mjs — DO NOT EDIT BY HAND.
 * Source: specs/witness/session/submit/0.1/payload.schema.json
 */

/**
 * A participating party submits its presentation bound to the session challenge; the witness's mandatory response delivers the Verifiable Witness Credential. The response is the outcome evidence a VWC presentation must ship.
 */
export interface WitnessSessionSubmitPayload {
  /**
   * A W3C Verifiable Presentation of the submitting party's own relationship credential material (opaque here), bound to the session's challenge and domain. A presentation not bound to this session is rejected with witness/session/submit:challengeMismatch.
   */
  vp: {};
  ext?: Ext;
}
/**
 * Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.
 */
export interface Ext {
  [k: string]: unknown | undefined;
}
/**
 * The Verifiable Witness Credential, delivered under the REQUIRED proof. This document is the ceremony's terminal success form and the outcome evidence a VWC presentation must ship.
 */
export interface WitnessSessionSubmitResponsePayload {
  /**
   * A signed Verifiable Witness Credential (opaque here; its schema belongs to DTG Core Credentials). Its taskContext MUST equal the id of the witness/session document that opened this ceremony — the innermost exchange that attests the witnessing (SPEC.md §4.9.1).
   */
  vwc: {};
  ext?: Ext;
}

/** Trust Task type URI. */
export const TYPE_URI = "https://trusttasks.org/spec/witness/session/submit/0.1" as const;

/** Stable alias for this specification's request payload shape. */
export type Payload = WitnessSessionSubmitPayload;

/** Trust Task response type URI (request type URI + "#response"). */
export const RESPONSE_TYPE_URI = "https://trusttasks.org/spec/witness/session/submit/0.1#response" as const;

/** Stable alias for this specification's success-response payload shape. */
export type Response = WitnessSessionSubmitResponsePayload;

/**
 * SPEC.md §7.2 policy for the request variant, from this specification's
 * front matter. Pass to `consumeInbound` — items 5b, 7 and 8 are
 * per-specification and cannot be derived from the document alone.
 */
export const SPEC = {
  typeUri: TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
} as const;

/**
 * SPEC.md §7.2 policy for the success-response variant. `isRecipientRequired`
 * tracks the *issuer* party's requirement because a response swaps the
 * parties (§7.3 item 5).
 */
export const RESPONSE_SPEC = {
  typeUri: RESPONSE_TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
} as const;
